// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	webhooks "github.com/cloudposse/atlantis/server/events/webhooks"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyWebhooksApplyResult() webhooks.ApplyResult {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(webhooks.ApplyResult))(nil)).Elem()))
	var nullValue webhooks.ApplyResult
	return nullValue
}

func EqWebhooksApplyResult(value webhooks.ApplyResult) webhooks.ApplyResult {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue webhooks.ApplyResult
	return nullValue
}
