// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	models "github.com/cloudposse/atlantis/server/events/models"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToModelsProjectLock() *models.ProjectLock {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*models.ProjectLock))(nil)).Elem()))
	var nullValue *models.ProjectLock
	return nullValue
}

func EqPtrToModelsProjectLock(value *models.ProjectLock) *models.ProjectLock {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *models.ProjectLock
	return nullValue
}
