// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"github.com/petergtz/pegomock"
	http "net/http"
	"reflect"
)

func AnyPtrToHttpRequest() *http.Request {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*http.Request))(nil)).Elem()))
	var nullValue *http.Request
	return nullValue
}

func EqPtrToHttpRequest(value *http.Request) *http.Request {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *http.Request
	return nullValue
}
