// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	events "github.com/runatlantis/atlantis/server/events"
)

func AnyEventsCommandName() models.CommandName {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.CommandName))(nil)).Elem()))
	var nullValue models.CommandName
	return nullValue
}

func EqEventsCommandName(value models.CommandName) models.CommandName {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.CommandName
	return nullValue
}
