// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	models "github.com/cloudposse/atlantis/server/events/models"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyModelsUser() models.User {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(models.User))(nil)).Elem()))
	var nullValue models.User
	return nullValue
}

func EqModelsUser(value models.User) models.User {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue models.User
	return nullValue
}
