// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	models "github.com/cloudposse/atlantis/server/events/models"
	"github.com/petergtz/pegomock"
	"reflect"
)

func AnyPtrToModelsRepo() *models.Repo {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*models.Repo))(nil)).Elem()))
	var nullValue *models.Repo
	return nullValue
}

func EqPtrToModelsRepo(value *models.Repo) *models.Repo {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *models.Repo
	return nullValue
}
